### ISSUE TITLE
IUserPolicyHandler interface should define method that returns bool for existence of a specific User Permission 

### ISSUE THREAD

**Issue by tedvanderveen** [pdevito3/HeimGuard#1]
The method `GetUserPermissions()` defined in interface `IUserPolicyHandler` requires all permissions for a user to be returned. Whilst at the moment of authorization execution, only 1 (or usually at most a handful) of required permissions is tested against the user's roles/permissions.

For example when maintaining Role memberships and Role permissions in an SQL database, it is a much more efficient (network)operation to merely evaluate SQL statement `EXISTS()` result, compared to loading a joined results set from a an SQL `SELECT` statement.

**Comment by pdevito3** [comment]
This is a good point, thanks for bringing it up. I'll try and find some time to get it in. Open to a PR if you'd like.
